### PR TITLE
feat: add fennel-language-server

### PR DESCRIPTION
**Pull request by Massolari**

### CODE REVIEW

**Comment by williamboman** [comment]
@williambotman /fixup

**Comment by williamboman** [comment]
Yep exactly!

**Comment by Massolari** [comment]
@williamboman It was merged!
Can you re-run the tasks?

**Comment by williamboman** [comment]
@williambotman /fixup

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/README.md b/README.md
index 8083d3f..fd17a50 100644
--- a/README.md
+++ b/README.md
@@ -193,6 +193,7 @@ local DEFAULT_SETTINGS = {
 | Erg                                 | `erg_language_server`      |
 | Erlang                              | `erlangls`                 |
 | F#                                  | `fsautocomplete`           |
+| Fennel                              | `fennel_language_server`   |
 | Flux                                | `flux_lsp`                 |
 | Foam (OpenFOAM)                     | `foam_ls`                  |
 | Fortran                             | `fortls`                   |
```

**Pull request merged**
