### PR TITLE
Add mappings and alias for the sonar lint server

### PR DESCRIPTION
**Pull request by asmodeus812**
Adding a new mapping for the sonar lint server to the global maps of language servers.

### CODE REVIEW

**Comment by williamboman** [comment]
@williambotman /fixup

**Review by williamboman — APPROVED** [review]
Thanks!

**Comment by williamboman** [comment]
Hm it seems like `sonarls` is not a valid nvim-lspconfig server configuration. There doesn't seem to be a PR in https://github.com/neovim/nvim-lspconfig to add it either?

**Comment by asmodeus812** [comment]
@williamboman well it is quite specific depending on the use case, it uses various adapters to work with different languages, there is no way to provide a generic config to make it work out of the box, it should be a custom config, added using the lspconfigs map.

**Comment by williamboman** [comment]
Hm ok. There are some server configurations with the same problematic in nvim-lspconfig, providing a default `cmd` is not always necessary. Anyways, if it's not available in nvim-lspconfig it can't be available in mason-lspconfig. Custom server configurations will have to be managed separately.

**Comment by asmodeus812** [comment]
@williamboman well instead of declining the pr how about you offer what we do here ? Do we add a server configuration with the cmd referencing all analyzers by default in lspconfig mason and have some generic table in nvim-lspconfig, without the cmd just the other basic required properties ?

**Comment by williamboman** [comment]
If it's possible to provide a meaningful, default, server configuration for it, then the server could be a good fit for nvim-lspconfig. If the server is added to nvim-lspconfig then yes mason-lspconfig is able to fill in the gaps in the default server configuration, for example providing a cmd.

**Pull request closed without merging**
