### PR TITLE
fix: rename `server_configurations` -> `configs`

### LINKED ISSUE #469: bug: nvim-lspconfig renamed server_configurations to configs
The following line errors when using latest nvim-lspconfig regardless of whether or not Omnisharp is used:

https://github.com/williamboman/mason-lspconfig.nvim/blob/25c11854aa25558ee6c03432edfa0df0217324be/lua/mason-lspconfig/server_config_extensions.lua#L4

This module was renamed in nvim-lspconfig by:

https://github.com/neovim/nvim-lspconfig/pull/3330

Example Error:

```log
[ERROR Wed  2 Oct 09:25:59 2024] ...m/lazy/mason-lspconfig.nvim/lua/mason-lspconfig/init.lua:33: Failed to set up lspconfig integration. ...ig.nvim/lua/mason-lspconfig/server_config_extensions.lua:4: module 'lspconfig.server_configurations.omnisharp' not found:
	no field package.preload['lspconfig.server_configurations.omnisharp']
cache_loader: module lspconfig.server_configurations.omnisharp not found
cache_loader_lib: module lspconfig.server_configurations.omnisharp not found
	no file './lspconfig/server_configurations/omnisharp.lua'
	no file '/opt/homebrew/share/luajit-2.1/lspconfig/server_configurations/omnisharp.lua'
	no file '/usr/local/share/lua/5.1/lspconfig/server_configurations/omnisharp.lua'
	no file '/usr/local/share/lua/5.1/lspconfig/server_configurations/omnisharp/init.lua'
	no file '/opt/homebrew/share/lua/5.1/lspconfig/server_configurations/omnisharp.lua'
	no file '/opt/homebrew/share/lua/5.1/lspconfig/server_configurations/omnisharp/init.lua'
	no file '/Users/XXXX/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/lspconfig/server_configurations/omnisharp.lua'
	no file '/Users/XXXX/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/lspconfig/server_configurations/omnisharp/init.lua'
	no file './lspconfig/server_configurations/omnisharp.so'
	no file '/usr/local/lib/lua/5.1/lspconfig/server_configurations/omnisharp.so'
	no file '/opt/homebrew/lib/lua/5.1/lspconfig/server_configurations/omnisharp.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/XXXX/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/lspconfig/server_configurations/omnisharp.so'
	no file './lspconfig.so'
	no file '/usr/local/lib/lua/5.1/lspconfig.so'
	no file '/opt/homebrew/lib/lua/5.1/lspconfig.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/XXXX/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/lspconfig.so'
```

### PR DESCRIPTION
**Pull request by mehalter**
A couple hours ago nvim-lspconfig just did a big refactor that renames the `server_configurations` modules to `configs`: https://github.com/neovim/nvim-lspconfig/pull/3330

This applies the rename here so that `mason-lspconfig` still functions. It is worth noting that `require("lspconfig.configs")` is still the same as before, it's just the default server configurations are now `"lspconfig.configs.<server_name>"`.

Another small change was moving from `:format()` to string concatenation. This isn't a huge deal, but in Lua simple string concatenation is marginally faster than string format.

Once this is merged in it is probably a good idea to do a quick patch version release for people who are tracking official releases since this is a pretty big breaking change 😄 

EDIT: Also applied changes necessary for other big changes/refactors in `nvim-lspconfig` in the past couple weeks. Total list of upstream PRs this takes into account:

- https://github.com/neovim/nvim-lspconfig/pull/3310
- https://github.com/neovim/nvim-lspconfig/pull/3324
- https://github.com/neovim/nvim-lspconfig/pull/3330
- https://github.com/neovim/nvim-lspconfig/pull/3358
- Removes support for Neovim <0.9. This is also just following suit with `nvim-lspconfig` since all the tests break. Once a v2.0 release is tagged here then people using an older version can simply use the last release here which also supports the last release of `nvim-lspconfig` with 0.7-0.8 support

Closes #469

### CODE REVIEW

**Comment by mehalter** [comment]
https://github.com/neovim/nvim-lspconfig/pull/3310

looks like `als` was also removed a couple weeks ago as well. I'll look into getting that resolved here as well.

**Comment by mehalter** [comment]
The only thing left to do here really is to decide if `mason-lspconfig` should also reflect these changes regarding `server_configurations` -> `configs`. I'll do a push with this refactor because I think over time it seems most logical to mirror the `nvim-lspconfig` structure, but if you want to keep it as before then I can easily revert that one change

**Comment by mehalter** [comment]
@williamboman sorry for the extra ping, I just wanted to see if this could get reviewed. Especially with the new neovim version release today I suspect a lot of people might be updating their configurations and this plugin will stop working in some regards with the changes to lspconfig

**Comment by jack-obrien** [comment]
Also, all the links in README.md need to get updated to point towards configs.md instead of server_configurations.md

**Comment by mehalter** [comment]
> Also, all the links in README.md need to get updated to point towards configs.md instead of server_configurations.md

Don't worry, that's already done in this PR :)

**Review by williamboman — APPROVED** [review]
Thanks and sorry for late review. I reverted the nvim 0.9.0 upgrade (which makes total sense, I'll add in a different PR for better changelog) and the mason-lspconfig module rename (I don't think this is necessary, might even be a breaking change to a handful users who override these modules).

**Comment by williamboman** [comment]
Oh nvim-lspconfig has a hard dependency on nvim 0.9, let me merge the nvim version requirement upgrade first and rebase

**Comment by mehalter** [comment]
Thanks so much! Let me know if you want me to do  anything else on this or if you want to handle the merging and stuff finishing up the rest of this. Glad to help contribute 😄

**Pull request merged**
