### PR TITLE
feat: add pest_ls and pest-language-server

### PR DESCRIPTION
**Pull request by Samyak2**
Depends on https://github.com/neovim/nvim-lspconfig/pull/2629 (that PR needs to be merged first)

### CODE REVIEW

**Comment by williamboman** [comment]
Thanks! Could you add an entry to the README table as well 🙏?

**Comment by Samyak2** [comment]
Done!

**Comment by Samyak2** [comment]
I don't understand the CI failure. Do I need to add pest_ls elsewhere too?

**Comment by williamboman** [comment]
@williambotman /fixup

**Pull request merged**
