### PR TITLE
feat(buf_ls): add buf_ls support

### PR DESCRIPTION
**Pull request by sprsquish**
Now that support has landed in [lspconfig](https://github.com/neovim/nvim-lspconfig/pull/3414), we can add it here.

Closes https://github.com/williamboman/mason-lspconfig.nvim/issues/488

### CODE REVIEW

**Comment by realSaltyFish** [comment]
Thanks for your work! `bufls` has been deprecated and will be removed from `lspconfig` soon. Would you mind also deleting `bufls` from the mapping?

**Comment by sprsquish** [comment]
> Would you mind also deleting `bufls` from the mapping?

done!

**Review by iliadmitriev — APPROVED** [review]
tested on my configuration with [astronvim](https://github.com/AstroNvim/AstroNvim) and `astrocommunity.pack.proto`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678

**Comment by fira42073** [comment]
This seems to solve [this issue](https://github.com/williamboman/mason-lspconfig.nvim/issues/488). Thanks for your contribution!!
Consider adding something like Closes #488

**Pull request merged**
