### PR TITLE
feat(registry): add brightscript

### PR DESCRIPTION
**Pull request by casonadams**

### CODE REVIEW

**Comment by casonadams** [comment]
I am not quite sure how this needs to line up with `lspconfig.nvim` I probably didn't do this correct because it is referred to as `bright_script` in the other repo.

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-lspconfig/mappings/server.lua b/lua/mason-lspconfig/mappings/server.lua
index c6d5597..b153f14 100644
--- a/lua/mason-lspconfig/mappings/server.lua
+++ b/lua/mason-lspconfig/mappings/server.lua
@@ -15,7 +15,7 @@ M.lspconfig_to_package = {
     ["bashls"] = "bash-language-server",
     ["beancount"] = "beancount-language-server",
     ["bicep"] = "bicep-lsp",
-    ["brightscript"] = "brightscript",
+    ["bright_script"] = "brighterscript",
     ["bsl_ls"] = "bsl-language-server",
     ["bufls"] = "buf-language-server",
     ["clangd"] = "clangd",
```

**Comment by williamboman** [comment]
@williambotman /fixup

**Review by williamboman — APPROVED** [review]
> I am not quite sure how this needs to line up with lspconfig.nvim I probably didn't do this correct because it is referred to as bright_script in the other repo.

Yeah it needs to be mapped to `bright_script`, but I updated it so it should be good now.

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/README.md b/README.md
index 1126eaa..8c900e8 100644
--- a/README.md
+++ b/README.md
@@ -159,6 +159,7 @@ local DEFAULT_SETTINGS = {
 | Bash                                | `bashls`                   |
 | Beancount                           | `beancount`                |
 | Bicep                               | `bicep`                    |
+| BrighterScript                      | `bright_script`            |
 | Buf                                 | `bufls`                    |
 | C                                   | `clangd`                   |
 | C#                                  | `csharp_ls`                |
```

**Pull request merged**
